#ifndef AUTONOMOUS_CONFIG
#define AUTONOMOUS_CONFIG

#define HOSTNAME              CONFIG_AUTONOMOUS_HOSTNAME

#define UART_PORT             CONFIG_AUTONOMOUS_UART_NUM
#define UART_TXD              CONFIG_AUTONOMOUS_UART_TXD
#define UART_RXD              CONFIG_AUTONOMOUS_UART_RXD

#define WIFI_SSID             CONFIG_AUTONOMOUS_WIFI_SSID
#define WIFI_PASS             CONFIG_AUTONOMOUS_WIFI_PASSWORD
#define WIFI_MAXIMUM_RETRY    CONFIG_AUTONOMOUS_WIFI_MAXIMUM_RETRY

#if CONFIG_AUTONOMOUS_WIFI_AUTH_WPA_PSK
#define WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA_PSK
#elif CONFIG_AUTONOMOUS_WIFI_AUTH_WPA2_PSK
#define WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA2_PSK
#elif CONFIG_AUTONOMOUS_WIFI_AUTH_WPA_WPA2_PSK
#define WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA_WPA2_PSK
#elif CONFIG_AUTONOMOUS_WIFI_AUTH_WPA3_PSK
#define WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA3_PSK
#elif CONFIG_AUTONOMOUS_WIFI_AUTH_WPA2_WPA3_PSK
#define WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA2_WPA3_PSK
#elif CONFIG_AUTONOMOUS_WIFI_AUTH_WAPI_PSK
#define WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WAPI_PSK
#endif

#define MQTT_BROKER_URL       CONFIG_AUTONOMOUS_MQTT_BROKER_URL
#define MQTT_BROKER_USERNAME  CONFIG_AUTONOMOUS_MQTT_BROKER_USERNAME
#define MQTT_BROKER_PASSWORD  CONFIG_AUTONOMOUS_MQTT_BROKER_PASSWORD

#endif // AUTONOMOUS_CONFIG
