#ifndef AUTONOMOUS_WIFI
#define AUTONOMOUS_WIFI

#include "esp_wifi.h"

#define HOSTNAME            CONFIG_AUTONOMOUS_HOSTNAME
#define WIFI_SSID           CONFIG_AUTONOMOUS_WIFI_SSID
#define WIFI_PASS           CONFIG_AUTONOMOUS_WIFI_PASSWORD
#define WIFI_RETRY_DELAY    (1000 / portTICK_PERIOD_MS)

#if CONFIG_AUTONOMOUS_WIFI_AUTH_WPA_PSK
#define WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA_PSK
#elif CONFIG_AUTONOMOUS_WIFI_AUTH_WPA2_PSK
#define WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA2_PSK
#elif CONFIG_AUTONOMOUS_WIFI_AUTH_WPA_WPA2_PSK
#define WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA_WPA2_PSK
#elif CONFIG_AUTONOMOUS_WIFI_AUTH_WPA3_PSK
#define WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA3_PSK
#elif CONFIG_AUTONOMOUS_WIFI_AUTH_WPA2_WPA3_PSK
#define WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA2_WPA3_PSK
#elif CONFIG_AUTONOMOUS_WIFI_AUTH_WAPI_PSK
#define WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WAPI_PSK
#endif

void wifi_init(void);

#endif // AUTONOMOUS_WIFI
